---
title: "Fiction Ero Physio"
editor: source
editor_options: 
  chunk_output_type: console
format:
  html:
    code-fold: true
    self-contained: true
---

## Data Preparation

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(easystats)
library(patchwork)
library(ggside)
library(readr)

```


```{r}
#| code-fold: false

df <- read_tsv("C:/Users/asf25/Box/FictionEroPhysio/Rebel - FictionEroPhysio/participants.tsv") |>
  select(!c("Comments_RS", "Comments_Fiction", "Comments_Intero", "Comments_General"))



```
The initial sample consisted of `r report::report_participants(df, age="Age", gender="Gender")`.

## Incentive 

```{r}
# Table
summarize(df, N = n(), .by=c("Incentive")) |> 
  arrange(desc(N)) |> 
  gt::gt() |> 
  gt::grand_summary_rows(columns = "N", fns = Total ~ sum(.)) |> 
  gt::opt_stylize(style = 2, color = "gray") |> 
  gt::tab_header("Number of participants per icentive") 
```

## Feedback 

```{r}
df |> 
  summarise(n = n(), .by=c("Experiment_Enjoyment")) |>
  filter(!is.na(Experiment_Enjoyment)) |> 
  mutate(n = n / sum(n),
         Experiment_Enjoyment = fct_rev(as.factor(Experiment_Enjoyment))) |>
  ggplot(aes(y = n, x = 1, fill = Experiment_Enjoyment)) +
  geom_bar(stat="identity", position="stack") +
  scale_fill_manual(values=c("green", "yellowgreen",  "yellow", "orange", "red")) +
  coord_flip() +
  scale_x_continuous(expand=c(0, 0))  +
  scale_y_continuous(labels = scales::percent)  +
  labs(title="Experiment Enjoyment",
       subtitle="Proportion of participants by condition") + 
  guides(fill = guide_legend(reverse=TRUE)) +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    legend.position = "top",
    legend.title = element_blank()) 
```


## Dimension Computation

::: {.panel-tabset}

### MINT

```{r}
compute_and_remove <- function(df, name="BodyAwareness", pattern=name, method="mean") {
  items <- select(df, starts_with(pattern), -contains("AttentionCheck"))
  df <- df[!names(df) %in% names(items)]
  if(method == "mean") {
    df[[name]] <- rowMeans(items, na.rm=TRUE)
  } else {
    df[[name]] <- rowSums(items, na.rm=TRUE)
  }
  df
}
```


```{r}
df <- compute_and_remove(df, name="MINT_Card", method="mean")
df <- compute_and_remove(df, name="MINT_Urin", method="mean")
df <- compute_and_remove(df, name="MINT_SexS", method="mean")
df <- compute_and_remove(df, name="MINT_Gast", method="mean")
df <- compute_and_remove(df, name="MINT_Olfa", method="mean")
df <- compute_and_remove(df, name="MINT_Derm", method="mean")
df <- compute_and_remove(df, name="MINT_ExAc", method="mean")
df <- compute_and_remove(df, name="MINT_ReIA", method="mean")
df <- compute_and_remove(df, name="MINT_Resp", method="mean")
df <- compute_and_remove(df, name="MINT_Sati", method="mean")
df <- compute_and_remove(df, name="MINT_CaCo", method="mean")

```

### MAIA

```{r}
df$MAIA_AttentionRegulation = rowSums(select(df, starts_with("MAIA_AttentionRegulation_"))) / 7 
df$MAIA_Noticing = rowSums(select(df, starts_with("MAIA_Noticing_"))) / 4

df$MAIA_SelfRegulation = rowSums(select(df, starts_with("MAIA_SelfRegulation_"))) / 4

df$MAIA_EmotionalAwareness = rowSums(select(df, starts_with("MAIA_EmotionalAwareness_"))) / 5

df$MAIA_BodyListening = rowSums(select(df, starts_with("MAIA_BodyListening_"))) / 3

df$MAIA_Trusting = rowSums(select(df, starts_with("MAIA_Trusting_"))) / 3

df$MAIA_NotDistracting_1_R <- 6-
df$MAIA_NotDistracting_1_R 

df$MAIA_NotDistracting_2_R <- 6-
df$MAIA_NotDistracting_2_R 

df$MAIA_NotDistracting_3_R <- 6-
df$MAIA_NotDistracting_3_R 

df$MAIA_NotDistracting_4_R <- 6-
df$MAIA_NotDistracting_4_R 

df$MAIA_NotDistracting_5_R <- 6-
df$MAIA_NotDistracting_5_R 

df$MAIA_NotDistracting_6_R <- 6-
df$MAIA_NotDistracting_6_R 

df$MAIA_NotDistracting = rowSums(select(df, starts_with("MAIA_NotDistracting_"))) / 6

df$MAIA_NotWorrying_1_R <- 6-
df$MAIA_NotWorrying_1_R 

df$MAIA_NotWorrying_2_R <- 6-
df$MAIA_NotWorrying_2_R 

df$MAIA_NotWorrying_5_R <- 6-
df$MAIA_NotWorrying_5_R

df$MAIA_NotWorrying = rowSums(select(df, starts_with("MAIA_NotWorrying_"))) / 5

```


```{r}
make_hist <- function(data, scales="fixed") {
  data |> 
    pivot_longer(cols = everything()) |>
    ggplot(aes(x=value, fill=name)) +
    geom_histogram(bins=30) +
    theme_minimal() +
    scale_fill_viridis_d(guide="none") +
    facet_wrap(~name, scales=scales)
}



select(df, starts_with("MAIA"), -matches("\\d$"), -contains("_R")) |> 
  make_hist() 
```


```{r}
make_correlation <- function(data, data2=NULL) {
  redundant <- TRUE
  if(!is.null(data2)) redundant <- FALSE
  cor <- data |> 
    correlation(data2=data2, method="pearson", redundant=redundant, p_adjust="none") |> 
    correlation::cor_sort() 
  
  if(is.null(data2)) cor <- correlation::cor_lower(cor) 
    
  cor |> 
    mutate(val = paste0(insight::format_value(r), format_p(p, stars_only=TRUE))) |>
    mutate(Parameter2 = fct_rev(Parameter2)) |>
    # mutate(Parameter1 = fct_relabel(Parameter1, \(x) str_remove_all(x, "Feedback_")),
    #        Parameter2 = fct_relabel(Parameter2, \(x) str_remove_all(x, "Feedback_"))) |>
    ggplot(aes(x=Parameter1, y=Parameter2)) +
    geom_tile(aes(fill = r), color = "white") +
    geom_text(aes(label = val), size = 3) +
    labs(title = "Correlation Matrix") +
    scale_fill_gradient2(
      low = "#2196F3",
      mid = "white",
      high = "#F44336",
      breaks = c(-1, 0, 1),
      guide = guide_colourbar(ticks=FALSE),
      midpoint = 0,
      na.value = "grey85",
      limit = c(-1, 1))  + 
    theme_minimal() +
    theme(legend.title = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1))
} 

select(df, starts_with("MAIA"), -matches("\\d$"), -contains("_R"))  |> 
  make_correlation()
```

### IAS 

```{r}
df$IAS_Total = rowSums(select(df, starts_with("IAS"), -"IAS_AttentionCheck_1")) / 21
```

```{r}
select(df, "IAS_Total") |> 
  make_hist(scales="free") 
```

### BAIT
```{r}
df$BAIT_Issues <- rowMeans(select(df, BAIT_8_TextIssues, BAIT_2_ImagesIssues, BAIT_3_VideosIssues), na.rm=TRUE)

df$BAIT_Realistic <- rowMeans(select(df, BAIT_5_ImitatingReality, BAIT_4_VideosRealistic, BAIT_1_ImagesRealistic, BAIT_6_EnvironmentReal, BAIT_7_TextRealistic), na.rm=TRUE)

df$BAIT_Negative <- rowMeans(select(df, BAIT_9_Dangerous, BAIT_10_Worry))

df$BAIT_Positive <- rowMeans(select(df, BAIT_12_Benefit, BAIT_11_Exciting), na.rm=TRUE)

# df$BAIT_Total <- rowMeans(select(mutate(
#   df, BAIT_Negative = abs(BAIT_Negative - 6),
#       BAIT_Issues = abs(BAIT_Issues - 6)), 
#   BAIT_Negative, BAIT_Positive, BAIT_Realistic, BAIT_Issues), na.rm=TRUE)

```

```{r}
select(df, "BAIT_Negative", "BAIT_Positive", "BAIT_Issues", "BAIT_Realistic", "BAIT_Total") |> 
  make_hist(scales="free") 
```

```{r}
df |> 
  select(starts_with("BAIT")) |>
  mutate(BAIT_AI_Use = case_when(
    BAIT_AI_Use == "Never" ~ 0,
    BAIT_AI_Use == "A few times per month" ~ 1,
    BAIT_AI_Use == "A few times per week" ~ 2,
    BAIT_AI_Use == "Once a day" ~ 3,
    BAIT_AI_Use == "A few times per day" ~ 4,
    .default = NA
  )) |> 
  correlation::correlation(redundant = TRUE) |> 
  correlation::cor_sort() |> 
  correlation::cor_lower() |> 
  summary() |> 
  plot(text = list(size = 2.5)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

:::

## Exclusions

```{r}
outliers <- list()
```

::: {.panel-tabset}

### Questionnaires

```{r}
outliers$ias <- df$participant_id[df$IAS_Total < 0.4]

df[df$participant_id %in% outliers$ias, str_detect(names(df), "IAS_")] <- NA
```

```{r}
dfchecks <- data.frame(
  Participant = df$participant_id,
  A_MINT = ifelse(df$MINT_AttentionCheck == 0, 0, 1),
  A_IAS = ifelse(df$IAS_AttentionCheck_1 == 1, 0, 1),
  A_BAIT = ifelse(df$BAIT_AttentionCheck == 6, 0, 1),
  A_MAIA = ifelse(df$MAIA_AttentionCheck_1 == 6, 0, 1)
)

summary(correlation(dfchecks))
```

